spring:
  application:
    name: api-gateway
  profiles:
    active: '@spring.profiles.active@'

---

spring:
  config:
    activate:
      on-profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 80

---

spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
server:
  port: 80