spring:
  application:
    name: auth-service
  profiles:
    active: '@spring.profiles.active@'

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: users_admin
    password: users_pass
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081

---

spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
server:
  port: 8081
